name: dartnow
authorKasper Peulen <kasperpeulen@gmail.com>: # name <email>
homepagehttp://dartnow.org: # https://github.com/user/repo
version: 0.1.0
environment:
  sdk: '>=1.11.0 <2.0.0'
description: Dart Now cli
dependencies:
  args: '^0.13.2'
  github: any
  yaml: any
  pubspec: any
  yamlicious: any
  prompt: '>=0.1.7 <0.2.0'
  http:
    git:
      url: ../../packages/http
      ref: 'patch'
  github:
    path: ../../packages/github.dart
  test: '>=0.12.3+7 <0.13.0'
  analyzer: '>=0.25.2 <0.26.0'
  path: '>=1.3.6 <2.0.0'

executables:
  dartnow:
  dartnow_admin: